packages:
  - "apps/*"
  - "modules/*"
  - "packages/*"
allowBuilds:
  '@swc/core': true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  ssh2: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.2'
  - '@turbo/darwin-arm64@2.11.2'
  - '@turbo/linux-64@2.11.2'
  - '@turbo/linux-arm64@2.11.2'
  - '@turbo/windows-64@2.11.2'
  - '@turbo/windows-arm64@2.11.2'
  - bullmq@6.3.8
  - eslint@10.11.0
  - turbo@2.11.2
